MLIR: mlir::sparse_tensor::LoopEmitter Class Reference
mlir::sparse_tensor::LoopEmitter Class Reference
#include "Dialect/SparseTensor/Transforms/LoopEmitter.h"
Public Types
using OutputUpdater = function_ref< Value(OpBuilder &builder, Location loc, Value memref, Value tensor)>
Optional callback function to setup dense output tensors when initializing the loop emitter (e.g., to fill a dense output with zeros).
using SynTensorBoundSetter = function_ref< Value(OpBuilder &builder, Location loc, Level lvl)>
Optional callback function to set the bound for the synthetic tensor, which essentially is the dense loop bound.
using DependentLvlGetter = function_ref< std::vector< std::pair< TensorLevel, unsigned > >(TensorId, Level)>
Public Member Functions
LoopEmitter ()=default
void initialize (ValueRange tensors, StringAttr loopTag=nullptr, bool hasOutput=false, bool isSparseOut=false, unsigned numLoops=0, DependentLvlGetter getter=nullptr)
Takes an array of input tensors, which the generated loops will iterate over.
LoopEmitter (ValueRange tensors, StringAttr loopTag=nullptr, bool hasOutput=false, bool isSparseOut=false, unsigned numLoops=0, DependentLvlGetter getter=nullptr)
void initializeLoopEmit (OpBuilder &builder, Location loc, OutputUpdater updater=nullptr, SynTensorBoundSetter synSetter=nullptr)
Starts a loop emitting session by generating all the buffers needed for iterating over the tensors.
Value genAffine (OpBuilder &builder, Location loc, AffineExpr a)
Generates code to compute an affine expression whose variables are LoopIds (i.e., a.cast<AffineDimExpr>().getPosition() is a valid LoopId).
void enterNewLoopSeq (OpBuilder &builder, Location loc, ArrayRef< TensorLevel > tidLvls)
Enters a new loop sequence, the loops within the same sequence starts from the break points of previous loop instead of starting over from 0.
void exitCurrentLoopSeq (OpBuilder &builder, Location loc)
Exits the current loop sequence, this will reset universal index to 0.
Operation * enterFilterLoopOverTensorAtLvl (OpBuilder &builder, Location loc, TensorId tid, Level lvl, AffineExpr affine, MutableArrayRef< Value > reduc={})
Enters a loop that tries to locate a coordinates in a sparse level based on the value evaluated by the provided affine expression.
void genDenseAffineAddress (OpBuilder &builder, Location loc, TensorLevel tidLvl, AffineExpr lvlExpr)
Emits the address for a dense level based on the value evaluated by the provided affine expression.
Operation * enterCoIterationOverTensorsAtLvls (OpBuilder &builder, Location loc, ArrayRef< TensorLevel > tidLvls, MutableArrayRef< Value > reduc={}, bool isParallel=false, bool genDedup=false, bool needsUniv=false)
Emits a co-iteration loop over a set of tensors.
void exitCurrentLoop (RewriterBase &rewriter, Location loc, MutableArrayRef< Value > reduc={})
Generates code to exit the current loop (e.g., generates yields, forwards loop induction variables, etc).
auto getLoopIVsRange () const
Get the range of values for all induction variables.
SmallVector< Value > getLoopIVs () const
Fills the out-parameter with the loop induction variables for all loops in the current loop-stack.
LoopId getCurrentDepth () const
Gets the current depth of the loop-stack.
Value getLoopIV (LoopId n) const
Gets loop induction variable for the given loop.
unsigned getNumManifestTensors () const
Gets the total number of manifest tensors (excluding the synthetic tensor).
unsigned getNumTensors () const
Gets the total number of tensors that loopEmitter is operating on.
TensorId getSynTensorId () const
Gets the TensorId for synthetic tensor.
TensorId getOutTensorId () const
Gets the TensorId for output tensor.
TensorLevel makeTensorLevel (TensorId t, Level l) const
Compresses a TensorId and Level into a TensorLevel.
std::pair< TensorId, Level > unpackTensorLevel (TensorLevel tidLvl) const
De-compresses a TensorLevel back to a pair of TensorId and Level.
template<class ContainerTy >
auto unpackTensorLevelRange (ContainerTy &&c) const
Converts a range of TensorLevel to a range of std::pair<TensorId, Level>
template<class ContainerTy >
auto unpackTensorLevelFromCondRange (ContainerTy &&c) const
const std::vector< std::vector< Value > > & getPosits () const
Getters.
const std::vector< std::vector< Value > > & getCoords () const
const std::vector< std::vector< Value > > & getHighs () const
const std::vector< std::vector< Value > > & getPositionBuffers () const
const std::vector< std::vector< Value > > & getCoordinateBuffers () const
const std::vector< Value > & getValBuffer () const
Static Public Member Functions
constexpr static llvm::StringLiteral getLoopEmitterLoopAttrName ()
Detailed Description
Definition at line 53 of file LoopEmitter.h.
Member Typedef Documentation
DependentLvlGetter
using mlir::sparse_tensor::LoopEmitter::DependentLvlGetter = function_ref<std::vector<std::pair<TensorLevel, unsigned> >(TensorId, Level)>
Definition at line 78 of file LoopEmitter.h.
OutputUpdater
using mlir::sparse_tensor::LoopEmitter::OutputUpdater = function_ref<Value(OpBuilder &builder, Location loc, Value memref, Value tensor)>
Optional callback function to setup dense output tensors when initializing the loop emitter (e.g., to fill a dense output with zeros).
Definition at line 57 of file LoopEmitter.h.
SynTensorBoundSetter
using mlir::sparse_tensor::LoopEmitter::SynTensorBoundSetter = function_ref<Value(OpBuilder &builder, Location loc, Level lvl)>
Optional callback function to set the bound for the synthetic tensor, which essentially is the dense loop bound.
Definition at line 62 of file LoopEmitter.h.
Constructor & Destructor Documentation
LoopEmitter() [1/2]
mlir::sparse_tensor::LoopEmitter::LoopEmitter () default
LoopEmitter() [2/2]
LoopEmitter::LoopEmitter (ValueRange tensors, StringAttr loopTag = nullptr, bool hasOutput = false, bool isSparseOut = false, unsigned numLoops = 0, DependentLvlGetter getter = nullptr) explicit
Definition at line 295 of file LoopEmitter.cpp.
References initialize().
Member Function Documentation
enterCoIterationOverTensorsAtLvls()
Operation * LoopEmitter::enterCoIterationOverTensorsAtLvls (OpBuilder & builder, Location loc, ArrayRef< TensorLevel > tidLvls, MutableArrayRef< Value > reduc = {}, bool isParallel = false, bool genDedup = false, bool needsUniv = false)
Emits a co-iteration loop over a set of tensors.
Emits loop over tensor_tid_lvl, it assumes that loops between tensor_tid_[0, lvl - 1] have already been generated. The function will also perform in-place update on the reduc vector to return the reduction variable used inside the generated loop.
Definition at line 1073 of file LoopEmitter.cpp.
References ADDI, C_IDX, DIVUI, mlir::OpBuilder::getInsertionBlock(), SUBI, unpackTensorLevel(), and unpackTensorLevelRange().
enterFilterLoopOverTensorAtLvl()
Operation * LoopEmitter::enterFilterLoopOverTensorAtLvl (OpBuilder & builder, Location loc, TensorId tid, Level lvl, AffineExpr affine, MutableArrayRef< Value > reduc = {})
Enters a loop that tries to locate a coordinates in a sparse level based on the value evaluated by the provided affine expression.
DEPRECATED: affine index expression should be handled by index reduction loop, filter loop-based solution is slow.
Definition at line 1169 of file LoopEmitter.cpp.
References C_IDX, CMPI, mlir::OpBuilder::create(), genAffine(), mlir::sparse_tensor::genIndexLoad(), mlir::OpBuilder::getInsertionBlock(), mlir::sparse_tensor::isDenseLT(), makeTensorLevel(), mlir::OpBuilder::setInsertionPointToStart(), and YIELD.
enterNewLoopSeq()
void LoopEmitter::enterNewLoopSeq (OpBuilder & builder, Location loc, ArrayRef< TensorLevel > tidLvls)
Enters a new loop sequence, the loops within the same sequence starts from the break points of previous loop instead of starting over from 0.
e.g., { // loop sequence start. p0 = while(xxx) ... break p0
// Starts loop from p0 for (i = p0; i < end; i++) ... // loop sequence end. }
Definition at line 580 of file LoopEmitter.cpp.
References C_IDX, and unpackTensorLevelRange().
Referenced by startLoopSeq().
exitCurrentLoop()
void LoopEmitter::exitCurrentLoop (RewriterBase & rewriter, Location loc, MutableArrayRef< Value > reduc = {})
Generates code to exit the current loop (e.g., generates yields, forwards loop induction variables, etc).
Definition at line 1553 of file LoopEmitter.cpp.
References mlir::OpBuilder::setInsertionPoint(), and mlir::OpBuilder::setInsertionPointToEnd().
exitCurrentLoopSeq()
void LoopEmitter::exitCurrentLoopSeq (OpBuilder & builder, Location loc)
Exits the current loop sequence, this will reset universal index to 0.
Definition at line 600 of file LoopEmitter.cpp.
Referenced by endLoopSeq().
genAffine()
Value LoopEmitter::genAffine (OpBuilder & builder, Location loc, AffineExpr a)
Generates code to compute an affine expression whose variables are LoopIds (i.e., a.cast<AffineDimExpr>().getPosition() is a valid LoopId).
Definition at line 617 of file LoopEmitter.cpp.
References mlir::Add, ADDI, C_IDX, mlir::Constant, mlir::DimId, mlir::AffineExpr::getKind(), mlir::Mul, and MULI.
Referenced by enterFilterLoopOverTensorAtLvl(), genDenseAffineAddress(), and genSubscript().
genDenseAffineAddress()
void LoopEmitter::genDenseAffineAddress (OpBuilder & builder, Location loc, TensorLevel tidLvl, AffineExpr lvlExpr)
Emits the address for a dense level based on the value evaluated by the provided affine expression.
DEPRECATED: affine index expression should be handled by index reduction loop, filter loop-based solution is slow.
Definition at line 1236 of file LoopEmitter.cpp.
References genAffine(), mlir::sparse_tensor::isDenseLT(), and unpackTensorLevel().
Referenced by startLoop().
getCoordinateBuffers()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::LoopEmitter::getCoordinateBuffers () const inline
Definition at line 248 of file LoopEmitter.h.
getCoords()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::LoopEmitter::getCoords () const inline
Definition at line 243 of file LoopEmitter.h.
Referenced by genIf().
getCurrentDepth()
LoopId mlir::sparse_tensor::LoopEmitter::getCurrentDepth () const inline
Gets the current depth of the loop-stack.
Definition at line 178 of file LoopEmitter.h.
References getLoopIVsRange().
Referenced by mlir::sparse_tensor::CodegenEnv::getCurrentDepth(), and getLoopIV().
getHighs()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::LoopEmitter::getHighs () const inline
Definition at line 244 of file LoopEmitter.h.
getLoopEmitterLoopAttrName()
constexpr static llvm::StringLiteral mlir::sparse_tensor::LoopEmitter::getLoopEmitterLoopAttrName () inline static constexpr
Definition at line 253 of file LoopEmitter.h.
Referenced by finalizeWhileOp().
getLoopIV()
Value mlir::sparse_tensor::LoopEmitter::getLoopIV (LoopId n) const inline
Gets loop induction variable for the given loop.
Definition at line 181 of file LoopEmitter.h.
References getCurrentDepth(), and getLoopIVsRange().
Referenced by mlir::sparse_tensor::CodegenEnv::getLoopVar().
getLoopIVs()
SmallVector<Value> mlir::sparse_tensor::LoopEmitter::getLoopIVs () const inline
Fills the out-parameter with the loop induction variables for all loops in the current loop-stack.
Definition at line 173 of file LoopEmitter.h.
References getLoopIVsRange().
getLoopIVsRange()
auto mlir::sparse_tensor::LoopEmitter::getLoopIVsRange () const inline
Get the range of values for all induction variables.
Definition at line 167 of file LoopEmitter.h.
Referenced by getCurrentDepth(), getLoopIV(), and getLoopIVs().
getNumManifestTensors()
unsigned mlir::sparse_tensor::LoopEmitter::getNumManifestTensors () const inline
Gets the total number of manifest tensors (excluding the synthetic tensor).
Definition at line 191 of file LoopEmitter.h.
Referenced by getNumTensors(), getOutTensorId(), initializeLoopEmit(), and mlir::sparse_tensor::CodegenEnv::makeTensorLevel().
getNumTensors()
unsigned mlir::sparse_tensor::LoopEmitter::getNumTensors () const inline
Gets the total number of tensors that loopEmitter is operating on.
Definition at line 194 of file LoopEmitter.h.
References getNumManifestTensors().
Referenced by mlir::sparse_tensor::CodegenEnv::makeTensorLevel(), makeTensorLevel(), and unpackTensorLevel().
getOutTensorId()
TensorId mlir::sparse_tensor::LoopEmitter::getOutTensorId () const inline
Gets the TensorId for output tensor.
Definition at line 203 of file LoopEmitter.h.
References getNumManifestTensors().
Referenced by mlir::sparse_tensor::CodegenEnv::makeTensorLevel().
getPositionBuffers()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::LoopEmitter::getPositionBuffers () const inline
Definition at line 245 of file LoopEmitter.h.
getPosits()
const std::vector<std::vector<Value> >& mlir::sparse_tensor::LoopEmitter::getPosits () const inline
Getters.
Definition at line 242 of file LoopEmitter.h.
Referenced by genSubscript().
getSynTensorId()
TensorId mlir::sparse_tensor::LoopEmitter::getSynTensorId () const inline
Gets the TensorId for synthetic tensor.
Definition at line 200 of file LoopEmitter.h.
Referenced by initializeLoopEmit(), and mlir::sparse_tensor::CodegenEnv::makeTensorLevel().
getValBuffer()
const std::vector<Value>& mlir::sparse_tensor::LoopEmitter::getValBuffer () const inline
Definition at line 251 of file LoopEmitter.h.
Referenced by genSubscript().
initialize()
void LoopEmitter::initialize (ValueRange tensors, StringAttr loopTag = nullptr, bool hasOutput = false, bool isSparseOut = false, unsigned numLoops = 0, DependentLvlGetter getter = nullptr)
Takes an array of input tensors, which the generated loops will iterate over.
Each tensor is given a TensorId (numerically equal to the position of that tensor Value in the array). Setting isSparseOut indicates that the sparse output tensor is empty, so the loop emitter will generate loops over it according to the level-sizes.
Definition at line 301 of file LoopEmitter.cpp.
References mlir::sparse_tensor::Dense, mlir::sparse_tensor::SparseTensorType::getEncoding(), mlir::sparse_tensor::SparseTensorType::getLvlRank(), mlir::sparse_tensor::getRankedTensorType(), mlir::Value::getType(), mlir::sparse_tensor::SparseTensorType::hasEncoding(), and mlir::sparse_tensor::isZeroRankedTensorOrScalar().
Referenced by LoopEmitter(), and mlir::sparse_tensor::CodegenEnv::startEmit().
initializeLoopEmit()
void LoopEmitter::initializeLoopEmit (OpBuilder & builder, Location loc, LoopEmitter::OutputUpdater updater = nullptr, LoopEmitter::SynTensorBoundSetter synSetter = nullptr)
Starts a loop emitting session by generating all the buffers needed for iterating over the tensors.
Definition at line 411 of file LoopEmitter.cpp.
References ADDI, C_IDX, mlir::sparse_tensor::constantZero(), mlir::OpBuilder::create(), genSliceOffset(), genSliceStride(), mlir::sparse_tensor::genToCoordinates(), mlir::sparse_tensor::genToPositions(), mlir::sparse_tensor::genToValues(), mlir::get(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexType(), mlir::OpBuilder::getInsertionPoint(), mlir::sparse_tensor::SparseTensorType::getLvlRank(), mlir::bufferization::getMemRefTypeWithFullyDynamicLayout(), getNumManifestTensors(), mlir::sparse_tensor::getSparseTensorType(), getSynTensorId(), mlir::Value::getType(), mlir::sparse_tensor::is2OutOf4LT(), mlir::sparse_tensor::isCompressedLT(), mlir::sparse_tensor::isDenseLT(), mlir::sparse_tensor::isLooseCompressedLT(), mlir::sparse_tensor::isSingletonLT(), MULI, and unpackTensorLevel().
makeTensorLevel()
TensorLevel mlir::sparse_tensor::LoopEmitter::makeTensorLevel (TensorId t, Level l) const inline
Compresses a TensorId and Level into a TensorLevel.
Definition at line 209 of file LoopEmitter.h.
References getNumTensors().
Referenced by enterFilterLoopOverTensorAtLvl(), and mlir::sparse_tensor::CodegenEnv::makeTensorLevel().
unpackTensorLevel()
std::pair<TensorId, Level> mlir::sparse_tensor::LoopEmitter::unpackTensorLevel (TensorLevel tidLvl) const inline
De-compresses a TensorLevel back to a pair of TensorId and Level.
Definition at line 214 of file LoopEmitter.h.
References getNumTensors().
Referenced by enterCoIterationOverTensorsAtLvls(), genDenseAffineAddress(), initializeLoopEmit(), mlir::sparse_tensor::CodegenEnv::unpackTensorLevel(), and unpackTensorLevelRange().
unpackTensorLevelFromCondRange()
template<class ContainerTy > auto mlir::sparse_tensor::LoopEmitter::unpackTensorLevelFromCondRange (ContainerTy && c) const inline
Definition at line 231 of file LoopEmitter.h.
References unpackTensorLevelRange().
unpackTensorLevelRange()
template<class ContainerTy > auto mlir::sparse_tensor::LoopEmitter::unpackTensorLevelRange (ContainerTy && c) const inline
Converts a range of TensorLevel to a range of std::pair<TensorId, Level>
Definition at line 221 of file LoopEmitter.h.
References unpackTensorLevel().
Referenced by enterCoIterationOverTensorsAtLvls(), enterNewLoopSeq(), unpackTensorLevelFromCondRange(), and mlir::sparse_tensor::CodegenEnv::unpackTensorLevelRange().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/Transforms/LoopEmitter.h
lib/Dialect/SparseTensor/Transforms/LoopEmitter.cpp