MLIR: lib/Dialect/SparseTensor/Transforms/LoopEmitter.cpp File Reference
LoopEmitter.cpp File Reference
#include "LoopEmitter.h"
#include "CodegenUtils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorType.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
Macros
#define CMPI(p, l, r)
#define C_IDX(v) (constantIndex(builder, loc, (v)))
#define YIELD(vs) (builder.create<scf::YieldOp>(loc, (vs)))
#define ADDI(lhs, rhs) (builder.create<arith::AddIOp>(loc, (lhs), (rhs)))
#define ANDI(lhs, rhs) (builder.create<arith::AndIOp>(loc, (lhs), (rhs)))
#define SUBI(lhs, rhs) (builder.create<arith::SubIOp>(loc, (lhs), (rhs)))
#define MULI(lhs, rhs) (builder.create<arith::MulIOp>(loc, (lhs), (rhs)))
#define REMUI(lhs, rhs) (builder.create<arith::RemUIOp>(loc, (lhs), (rhs)))
#define DIVUI(lhs, rhs) (builder.create<arith::DivUIOp>(loc, (lhs), (rhs)))
#define SELECT(c, l, r) (builder.create<arith::SelectOp>(loc, (c), (l), (r)))
Enumerations
enum class SlicePosKind { kLo , kHi , kNext }
Functions
static LLVM_ATTRIBUTE_UNUSED void dumpIndexMemRef (OpBuilder &builder, Location loc, Value memref)
static Value genSliceOffset (OpBuilder &builder, Location loc, Value tensor, Level lvl)
static Value genSliceStride (OpBuilder &builder, Location loc, Value tensor, Level lvl)
static Value toSliceCrd (OpBuilder &builder, Location loc, Value crd, Value offset, Value stride, Value tensor, Level lvl)
Converts a coordinate relative to the slice to the coordinate relative to the underlying tensor.
static Value offsetFromMinCoord (OpBuilder &builder, Location loc, Value minCrd, Value size, Value isNonEmpty)
Generates code to compute the absolute offset of the slice based on the provide minimum coordinates in the slice.
static std::pair< Value, Value > fromSliceCrd (OpBuilder &builder, Location loc, Value crd, Value offset, Value stride, Value tensor, Level lvl)
Converts a coordinate relative to the underlying tensor to the coordinate relative to the slice, returns a extra reminder value.
static Value genSparseReducedAffineCond (OpBuilder &builder, Location loc, Value crdBuf, Value crdHi, Value posit, Value posHi)
static Value allocSlicePosBuf (OpBuilder &builder, Location loc, Value tupleCnt)
static Value getSlicePosIdx (OpBuilder &builder, Location loc, Value posBuf, Value tupleIdx, SlicePosKind posKind)
static Value loadSlicePos (OpBuilder &builder, Location loc, Value sPosBuf, Value tupleIdx, SlicePosKind posKind)
static void updateSlicePos (OpBuilder &builder, Location loc, Value sPosBuf, Value pos, Value tupleIdx, SlicePosKind posKind)
Variables
static constexpr unsigned kSliceIterWidth = 3
Macro Definition Documentation
ADDI
#define ADDI (lhs, rhs) (builder.create<arith::AddIOp>(loc, (lhs), (rhs)))
Definition at line 35 of file LoopEmitter.cpp.
ANDI
#define ANDI (lhs, rhs) (builder.create<arith::AndIOp>(loc, (lhs), (rhs)))
Definition at line 36 of file LoopEmitter.cpp.
C_IDX
#define C_IDX (v) (constantIndex(builder, loc, (v)))
Definition at line 33 of file LoopEmitter.cpp.
CMPI
#define CMPI (p, l, r)
Value:
  (builder.create<arith::CmpIOp>(loc, arith::CmpIPredicate::p, (l), (r))       \
       .getResult())
Definition at line 29 of file LoopEmitter.cpp.
DIVUI
#define DIVUI (lhs, rhs) (builder.create<arith::DivUIOp>(loc, (lhs), (rhs)))
Definition at line 40 of file LoopEmitter.cpp.
MULI
#define MULI (lhs, rhs) (builder.create<arith::MulIOp>(loc, (lhs), (rhs)))
Definition at line 38 of file LoopEmitter.cpp.
REMUI
#define REMUI (lhs, rhs) (builder.create<arith::RemUIOp>(loc, (lhs), (rhs)))
Definition at line 39 of file LoopEmitter.cpp.
SELECT
#define SELECT (c, l, r) (builder.create<arith::SelectOp>(loc, (c), (l), (r)))
Definition at line 41 of file LoopEmitter.cpp.
SUBI
#define SUBI (lhs, rhs) (builder.create<arith::SubIOp>(loc, (lhs), (rhs)))
Definition at line 37 of file LoopEmitter.cpp.
YIELD
#define YIELD (vs) (builder.create<scf::YieldOp>(loc, (vs)))
Definition at line 34 of file LoopEmitter.cpp.
Enumeration Type Documentation
SlicePosKind
enum SlicePosKind strong
Enumerator
kLo
kHi
kNext
Definition at line 162 of file LoopEmitter.cpp.
Function Documentation
allocSlicePosBuf()
static Value allocSlicePosBuf (OpBuilder & builder, Location loc, Value tupleCnt) static
Definition at line 154 of file LoopEmitter.cpp.
References C_IDX, mlir::sparse_tensor::genAlloca(), mlir::Builder::getIndexType(), kSliceIterWidth, and MULI.
dumpIndexMemRef()
static LLVM_ATTRIBUTE_UNUSED void dumpIndexMemRef (OpBuilder & builder, Location loc, Value memref) static
Definition at line 48 of file LoopEmitter.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::createFuncCall(), mlir::get(), mlir::Builder::getIndexType(), and mlir::sparse_tensor::On.
fromSliceCrd()
static std::pair<Value, Value> fromSliceCrd (OpBuilder & builder, Location loc, Value crd, Value offset, Value stride, Value tensor, Level lvl) static
Converts a coordinate relative to the underlying tensor to the coordinate relative to the slice, returns a extra reminder value.
Definition at line 115 of file LoopEmitter.cpp.
References DIVUI, REMUI, and SUBI.
genSliceOffset()
static Value genSliceOffset (OpBuilder & builder, Location loc, Value tensor, Level lvl) static
Definition at line 68 of file LoopEmitter.cpp.
References mlir::sparse_tensor::createOrFoldSliceOffsetOp(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), and mlir::sparse_tensor::toDim().
Referenced by mlir::sparse_tensor::LoopEmitter::initializeLoopEmit().
genSliceStride()
static Value genSliceStride (OpBuilder & builder, Location loc, Value tensor, Level lvl) static
Definition at line 74 of file LoopEmitter.cpp.
References mlir::sparse_tensor::createOrFoldSliceStrideOp(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), and mlir::sparse_tensor::toDim().
Referenced by mlir::sparse_tensor::LoopEmitter::initializeLoopEmit().
genSparseReducedAffineCond()
static Value genSparseReducedAffineCond (OpBuilder & builder, Location loc, Value crdBuf, Value crdHi, Value posit, Value posHi) static
Definition at line 128 of file LoopEmitter.cpp.
References CMPI, mlir::sparse_tensor::constantI1(), mlir::OpBuilder::create(), mlir::sparse_tensor::genIndexLoad(), mlir::Builder::getI1Type(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and YIELD.
getSlicePosIdx()
static Value getSlicePosIdx (OpBuilder & builder, Location loc, Value posBuf, Value tupleIdx, SlicePosKind posKind) static
Definition at line 163 of file LoopEmitter.cpp.
References ADDI, C_IDX, mlir::OpBuilder::create(), DIVUI, kHi, kLo, kNext, kSliceIterWidth, and MULI.
Referenced by loadSlicePos(), and updateSlicePos().
loadSlicePos()
static Value loadSlicePos (OpBuilder & builder, Location loc, Value sPosBuf, Value tupleIdx, SlicePosKind posKind) static
Definition at line 177 of file LoopEmitter.cpp.
References mlir::sparse_tensor::genIndexLoad(), and getSlicePosIdx().
offsetFromMinCoord()
static Value offsetFromMinCoord (OpBuilder & builder, Location loc, Value minCrd, Value size, Value isNonEmpty) static
Generates code to compute the absolute offset of the slice based on the provide minimum coordinates in the slice.
E.g., when reducing d0 + d1 + d2, we need two slices to fully reduced the expression, i,e, s1 = slice(T, d0), s2 = slice(s1, d1). The absolute offset is the offset computed relative to the initial tensors T.
When isNonEmpty == true, the computed offset is meaningless and should not be used during runtime, the method generates code to return 0 currently in that case.
offset = isNonEmpty && minCrd >= size ? minCrd - size + 1 : 0;
Definition at line 101 of file LoopEmitter.cpp.
References ADDI, ANDI, C_IDX, CMPI, SELECT, and SUBI.
toSliceCrd()
static Value toSliceCrd (OpBuilder & builder, Location loc, Value crd, Value offset, Value stride, Value tensor, Level lvl) static
Converts a coordinate relative to the slice to the coordinate relative to the underlying tensor.
Definition at line 84 of file LoopEmitter.cpp.
References ADDI, and MULI.
updateSlicePos()
static void updateSlicePos (OpBuilder & builder, Location loc, Value sPosBuf, Value pos, Value tupleIdx, SlicePosKind posKind) static
Definition at line 182 of file LoopEmitter.cpp.
References mlir::OpBuilder::create(), and getSlicePosIdx().
Variable Documentation
kSliceIterWidth
constexpr unsigned kSliceIterWidth = 3 static constexpr
Definition at line 66 of file LoopEmitter.cpp.
Referenced by allocSlicePosBuf(), and getSlicePosIdx().