MLIR: mlir::arm_sme Namespace Reference
mlir::arm_sme Namespace Reference
Functions
std::unique_ptr< Pass > createEnableArmStreamingPass (const ArmStreamingMode=ArmStreamingMode::Streaming, const ArmZaMode=ArmZaMode::Disabled, bool onlyIfRequiredByOps=false)
Pass to enable Armv9 Streaming SVE mode.
std::unique_ptr< Pass > createTileAllocationPass ()
Pass that allocates tile IDs to ArmSME operations.
void populateVectorTransferLoweringPatterns (LLVMTypeConverter &converter, RewritePatternSet &patterns)
unsigned getSMETileSliceMinNumElts (Type type)
Return minimum number of elements for the given element type in a vector of SVL bits.
bool isValidSMETileElementType (Type type)
Returns true if type is a valid element type for an SME tile or false otherwise.
bool isValidSMETileVectorType (VectorType vType)
Returns true if vType is a valid vector type for an SME tile or false otherwise.
std::optional< ArmSMETileType > getSMETileType (VectorType)
Returns the type of SME tile this vector type corresponds to, or none if the vector type does not fit within an SME tile.
LogicalResult verifyOperationHasValidTileId (Operation *)
Verifies the tile ID (if set) on this tile operation is valid.
Variables
constexpr unsigned MinStreamingVectorLengthInBits = 128
Function Documentation
createEnableArmStreamingPass()
std::unique_ptr< Pass > mlir::arm_sme::createEnableArmStreamingPass (const ArmStreamingMode streamingMode = ArmStreamingMode::Streaming, const ArmZaMode zaMode = ArmZaMode::Disabled, bool onlyIfRequiredByOps = false)
Pass to enable Armv9 Streaming SVE mode.
Definition at line 100 of file EnableArmStreaming.cpp.
createTileAllocationPass()
std::unique_ptr< Pass > mlir::arm_sme::createTileAllocationPass ()
Pass that allocates tile IDs to ArmSME operations.
Definition at line 280 of file TileAllocation.cpp.
getSMETileSliceMinNumElts()
unsigned mlir::arm_sme::getSMETileSliceMinNumElts (Type type)
Return minimum number of elements for the given element type in a vector of SVL bits.
Definition at line 18 of file Utils.cpp.
References mlir::Type::getIntOrFloatBitWidth(), isValidSMETileElementType(), and MinStreamingVectorLengthInBits.
Referenced by isValidSMETileVectorType().
getSMETileType()
std::optional< ArmSMETileType > mlir::arm_sme::getSMETileType (VectorType type)
Returns the type of SME tile this vector type corresponds to, or none if the vector type does not fit within an SME tile.
Definition at line 44 of file Utils.cpp.
References isValidSMETileVectorType().
isValidSMETileElementType()
bool mlir::arm_sme::isValidSMETileElementType (Type type)
Returns true if type is a valid element type for an SME tile or false otherwise.
Definition at line 23 of file Utils.cpp.
References mlir::Type::isBF16(), mlir::Type::isF128(), mlir::Type::isF16(), mlir::Type::isF32(), mlir::Type::isF64(), and mlir::Type::isInteger().
Referenced by getSMETileSliceMinNumElts(), and isValidSMETileVectorType().
isValidSMETileVectorType()
bool mlir::arm_sme::isValidSMETileVectorType (VectorType vType)
Returns true if vType is a valid vector type for an SME tile or false otherwise.
Definition at line 29 of file Utils.cpp.
References getSMETileSliceMinNumElts(), and isValidSMETileElementType().
Referenced by getSMETileType(), and mlir::populateArmSMEToLLVMConversionPatterns().
populateVectorTransferLoweringPatterns()
void mlir::arm_sme::populateVectorTransferLoweringPatterns (LLVMTypeConverter & converter, RewritePatternSet & patterns)
Referenced by mlir::populateVectorToLLVMConversionPatterns().
verifyOperationHasValidTileId()
LogicalResult mlir::arm_sme::verifyOperationHasValidTileId (Operation * op)
Verifies the tile ID (if set) on this tile operation is valid.
Definition at line 63 of file Utils.cpp.
Variable Documentation
MinStreamingVectorLengthInBits
constexpr unsigned mlir::arm_sme::MinStreamingVectorLengthInBits = 128 constexpr
Definition at line 24 of file Utils.h.
Referenced by getSMETileSliceMinNumElts().