MLIR: mlir::mesh Namespace Reference
mlir::mesh Namespace Reference
Namespaces
detail
Classes
struct ShardingOption
Typedefs
using ShardingArray = SmallVector< SmallVector< int32_t > >
using ShardingArrayRef = ArrayRef< SmallVector< int32_t > >
Functions
FailureOr< std::pair< bool, MeshShardingAttr > > getMeshShardingAttr (OpResult result)
FailureOr< std::pair< bool, MeshShardingAttr > > getMeshShardingAttr (OpOperand &opOperand)
bool isReductionLoop (IteratorType iType)
bool areReductionAndPartialMatch (IteratorType iType, Partial partial)
template<typename T >
void removeTrailingEmptySubArray (SmallVector< SmallVector< T >> &array)
Partial getPartialTypeFromReduction (IteratorType iType)
Typedef Documentation
ShardingArray
using mlir::mesh::ShardingArray = typedef SmallVector<SmallVector<int32_t> >
Definition at line 21 of file ShardingInterface.h.
ShardingArrayRef
using mlir::mesh::ShardingArrayRef = typedef ArrayRef<SmallVector<int32_t> >
Definition at line 22 of file ShardingInterface.h.
Function Documentation
areReductionAndPartialMatch()
bool mlir::mesh::areReductionAndPartialMatch (IteratorType iType, Partial partial)
Definition at line 120 of file MeshOps.cpp.
getMeshShardingAttr() [1/2]
FailureOr< std::pair< bool, MeshShardingAttr > > mlir::mesh::getMeshShardingAttr (OpOperand & opOperand)
Definition at line 140 of file ShardingInterface.cpp.
References mlir::failure(), mlir::IROperand< DerivedT, IRValueT >::get(), and mlir::Value::getDefiningOp().
getMeshShardingAttr() [2/2]
FailureOr< std::pair< bool, MeshShardingAttr > > mlir::mesh::getMeshShardingAttr (OpResult result)
Definition at line 96 of file ShardingInterface.cpp.
References mlir::Value::cast(), mlir::failure(), mlir::Value::getUsers(), and mlir::Value::hasOneUse().
getPartialTypeFromReduction()
Partial mlir::mesh::getPartialTypeFromReduction (IteratorType iType)
Definition at line 128 of file MeshOps.cpp.
isReductionLoop()
bool mlir::mesh::isReductionLoop (IteratorType iType)
Definition at line 116 of file MeshOps.cpp.
removeTrailingEmptySubArray()
template<typename T > void mlir::mesh::removeTrailingEmptySubArray (SmallVector< SmallVector< T >> & array)
Definition at line 38 of file MeshOps.h.