MLIR: lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp File Reference
OpenMPToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/OpenMP/OpenMPDialect.h"
#include "mlir/Dialect/OpenMP/OpenMPInterfaces.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Target/LLVMIR/Dialect/OpenMPCommon.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Frontend/OpenMP/OMPConstants.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <any>
#include <optional>
#include <utility>
Classes
struct MapInfoData
Functions
static llvm::OpenMPIRBuilder::InsertPointTy findAllocaInsertPoint (llvm::IRBuilderBase &builder, const LLVM::ModuleTranslation &moduleTranslation)
Find the insertion point for allocas given the current insertion point for normal operations in the builder.
static llvm::BasicBlock * convertOmpOpRegions (Region &region, StringRef blockName, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, LogicalResult &bodyGenStatus, SmallVectorImpl< llvm::PHINode * > *continuationBlockPHIs=nullptr)
Converts the given region that appears within an OpenMP dialect operation to LLVM IR, creating a branch from the sourceBlock to the entry block of the region, and a branch from any block with an successor-less OpenMP terminator to continuationBlock.
static llvm::omp::ProcBindKind getProcBindKind (omp::ClauseProcBindKind kind)
Convert ProcBindKind from MLIR-generated enum to LLVM enum.
static LogicalResult convertOmpMaster (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'master' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpCritical (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'critical' operation into LLVM IR using OpenMPIRBuilder.
template<typename T >
static std::optional< omp::ReductionDeclareOp > findReductionDeclInContainer (T container, omp::ReductionOp reduction)
Returns a reduction declaration that corresponds to the given reduction operation in the given container.
static omp::ReductionDeclareOp findReductionDecl (Operation &containerOp, omp::ReductionOp reduction)
Searches for a reduction in a provided region and the regions it is nested in.
template<typename T >
static void collectReductionDecls (T loop, SmallVectorImpl< omp::ReductionDeclareOp > &reductions)
Populates reductions with reduction declarations used in the given loop.
static LogicalResult inlineConvertOmpRegions (Region &region, StringRef blockName, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, SmallVectorImpl< llvm::Value * > *continuationBlockArgs=nullptr)
Translates the blocks contained in the given region and appends them to at the current insertion point of builder.
static OwningReductionGen makeReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Create an OpenMPIRBuilder-compatible reduction generator for the given reduction declaration.
static OwningAtomicReductionGen makeAtomicReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Create an OpenMPIRBuilder-compatible atomic reduction generator for the given reduction declaration.
static LogicalResult convertOmpOrdered (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'ordered' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpOrderedRegion (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'ordered_region' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpSections (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
static LogicalResult convertOmpSingle (omp::SingleOp &singleOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP single construct into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpTeams (omp::TeamsOp op, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
static LogicalResult convertOmpTaskOp (omp::TaskOp taskOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP task construct into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpTaskgroupOp (omp::TaskGroupOp tgOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP taskgroup construct into LLVM IR using OpenMPIRBuilder.
template<typename T >
static void allocReductionVars (T loop, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, llvm::OpenMPIRBuilder::InsertPointTy &allocaIP, SmallVector< omp::ReductionDeclareOp > &reductionDecls, SmallVector< llvm::Value * > &privateReductionVariables, DenseMap< Value, llvm::Value * > &reductionVariableMap)
Allocate space for privatized reduction variables.
template<typename T >
static void collectReductionInfo (T loop, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, SmallVector< omp::ReductionDeclareOp > &reductionDecls, SmallVector< OwningReductionGen > &owningReductionGens, SmallVector< OwningAtomicReductionGen > &owningAtomicReductionGens, const SmallVector< llvm::Value * > &privateReductionVariables, SmallVector< llvm::OpenMPIRBuilder::ReductionInfo > &reductionInfos)
Collect reduction info.
static LogicalResult convertOmpWsLoop (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP workshare loop into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpParallel (omp::ParallelOp opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts the OpenMP parallel operation to LLVM IR.
static LogicalResult convertOmpSimdLoop (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP simd loop into LLVM IR using OpenMPIRBuilder.
static llvm::AtomicOrdering convertAtomicOrdering (std::optional< omp::ClauseMemoryOrderKind > ao)
Convert an Atomic Ordering attribute to llvm::AtomicOrdering.
static LogicalResult convertOmpAtomicRead (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Convert omp.atomic.read operation to LLVM IR.
static LogicalResult convertOmpAtomicWrite (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an omp.atomic.write operation to LLVM IR.
llvm::AtomicRMWInst::BinOp convertBinOpToAtomic (Operation &op)
Converts an LLVM dialect binary operation to the corresponding enum value for atomicrmw supported binary operation.
static LogicalResult convertOmpAtomicUpdate (omp::AtomicUpdateOp &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP atomic update operation using OpenMPIRBuilder.
static LogicalResult convertOmpAtomicCapture (omp::AtomicCaptureOp atomicCaptureOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
static LogicalResult convertOmpReductionOp (omp::ReductionOp reductionOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP reduction operation using OpenMPIRBuilder.
static LogicalResult convertOmpThreadprivate (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP Threadprivate operation into LLVM IR using OpenMPIRBuilder.
static llvm::OffloadEntriesInfoManager::OMPTargetDeviceClauseKind convertToDeviceClauseKind (mlir::omp::DeclareTargetDeviceType deviceClause)
static llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryKind convertToCaptureClauseKind (mlir::omp::DeclareTargetCaptureClause captureClasue)
static llvm::SmallString< 64 > getDeclareTargetRefPtrSuffix (LLVM::GlobalOp globalOp, llvm::OpenMPIRBuilder &ompBuilder)
static llvm::Value * getRefPtrIfDeclareTarget (mlir::Value value, LLVM::ModuleTranslation &moduleTranslation)
uint64_t getArrayElementSizeInBits (LLVM::LLVMArrayType arrTy, DataLayout &dl)
llvm::Value * getSizeInBytes (DataLayout &dl, const mlir::Type &type, Operation *clauseOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
void collectMapDataFromMapOperands (MapInfoData &mapData, llvm::SmallVectorImpl< Value > &mapOperands, LLVM::ModuleTranslation &moduleTranslation, DataLayout &dl, llvm::IRBuilderBase &builder)
static void genMapInfos (llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, DataLayout &dl, llvm::OpenMPIRBuilder::MapInfosTy &combinedInfo, MapInfoData &mapData, const SmallVector< Value > &devPtrOperands={}, const SmallVector< Value > &devAddrOperands={}, bool isTargetParams=false)
static LogicalResult convertOmpTargetData (Operation *op, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
LogicalResult convertFlagsAttr (Operation *op, mlir::omp::FlagsAttr attribute, LLVM::ModuleTranslation &moduleTranslation)
Lowers the FlagsAttr which is applied to the module on the device pass when offloading, this attribute contains OpenMP RTL globals that can be passed as flags to the frontend, otherwise they are set to default.
static bool getTargetEntryUniqueInfo (llvm::TargetRegionEntryInfo &targetInfo, omp::TargetOp targetOp, llvm::StringRef parentName="")
static bool targetOpSupported (Operation &opInst)
static void handleDeclareTargetMapVar (MapInfoData &mapData, LLVM::ModuleTranslation &moduleTranslation, llvm::IRBuilderBase &builder)
static llvm::IRBuilderBase::InsertPoint createDeviceArgumentAccessor (MapInfoData &mapData, llvm::Argument &arg, llvm::Value *input, llvm::Value *&retVal, llvm::IRBuilderBase &builder, llvm::OpenMPIRBuilder &ompBuilder, LLVM::ModuleTranslation &moduleTranslation, llvm::IRBuilderBase::InsertPoint allocaIP, llvm::IRBuilderBase::InsertPoint codeGenIP)
static void createAlteredByCaptureMap (MapInfoData &mapData, LLVM::ModuleTranslation &moduleTranslation, llvm::IRBuilderBase &builder)
static LogicalResult convertOmpTarget (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
static LogicalResult convertDeclareTargetAttr (Operation *op, mlir::omp::DeclareTargetAttr attribute, LLVM::ModuleTranslation &moduleTranslation)
static LogicalResult convertRequiresAttr (Operation &op, omp::ClauseRequiresAttr requiresAttr, LLVM::ModuleTranslation &moduleTranslation)
Converts the module-level set of OpenMP requires clauses into LLVM IR using OpenMPIRBuilder.
Function Documentation
allocReductionVars()
template<typename T > static void allocReductionVars (T loop, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, llvm::OpenMPIRBuilder::InsertPointTy & allocaIP, SmallVector< omp::ReductionDeclareOp > & reductionDecls, SmallVector< llvm::Value * > & privateReductionVariables, DenseMap< Value, llvm::Value * > & reductionVariableMap) static
Allocate space for privatized reduction variables.
Definition at line 783 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::LLVM::ModuleTranslation::convertType().
Referenced by convertOmpParallel(), and convertOmpWsLoop().
collectMapDataFromMapOperands()
void collectMapDataFromMapOperands (MapInfoData & mapData, llvm::SmallVectorImpl< Value > & mapOperands, LLVM::ModuleTranslation & moduleTranslation, DataLayout & dl, llvm::IRBuilderBase & builder)
Definition at line 1726 of file OpenMPToLLVMIRTranslation.cpp.
References MapInfoData::BaseType, mlir::LLVM::ModuleTranslation::convertType(), mlir::LLVM::createMappingInformation(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), getRefPtrIfDeclareTarget(), getSizeInBytes(), MapInfoData::IsDeclareTarget, mlir::LLVM::ModuleTranslation::lookupValue(), MapInfoData::MapClause, None, and MapInfoData::OriginalValue.
Referenced by convertOmpTarget().
collectReductionDecls()
template<typename T > static void collectReductionDecls (T loop, SmallVectorImpl< omp::ReductionDeclareOp > & reductions) static
Populates reductions with reduction declarations used in the given loop.
Definition at line 383 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpParallel(), and convertOmpWsLoop().
collectReductionInfo()
template<typename T > static void collectReductionInfo (T loop, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, SmallVector< omp::ReductionDeclareOp > & reductionDecls, SmallVector< OwningReductionGen > & owningReductionGens, SmallVector< OwningAtomicReductionGen > & owningAtomicReductionGens, const SmallVector< llvm::Value * > & privateReductionVariables, SmallVector< llvm::OpenMPIRBuilder::ReductionInfo > & reductionInfos) static
Collect reduction info.
Definition at line 805 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::LLVM::ModuleTranslation::convertType(), mlir::LLVM::ModuleTranslation::lookupValue(), makeAtomicReductionGen(), and makeReductionGen().
Referenced by convertOmpParallel(), and convertOmpWsLoop().
convertAtomicOrdering()
static llvm::AtomicOrdering convertAtomicOrdering (std::optional< omp::ClauseMemoryOrderKind > ao) static
Convert an Atomic Ordering attribute to llvm::AtomicOrdering.
Definition at line 1214 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpAtomicCapture(), convertOmpAtomicRead(), convertOmpAtomicUpdate(), and convertOmpAtomicWrite().
convertBinOpToAtomic()
llvm::AtomicRMWInst::BinOp convertBinOpToAtomic (Operation & op)
Converts an LLVM dialect binary operation to the corresponding enum value for atomicrmw supported binary operation.
Definition at line 1276 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpAtomicCapture(), and convertOmpAtomicUpdate().
convertDeclareTargetAttr()
static LogicalResult convertDeclareTargetAttr (Operation * op, mlir::omp::DeclareTargetAttr attribute, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 2429 of file OpenMPToLLVMIRTranslation.cpp.
convertFlagsAttr()
LogicalResult convertFlagsAttr (Operation * op, mlir::omp::FlagsAttr attribute, LLVM::ModuleTranslation & moduleTranslation)
Lowers the FlagsAttr which is applied to the module on the device pass when offloading, this attribute contains OpenMP RTL globals that can be passed as flags to the frontend, otherwise they are set to default.
Definition at line 2014 of file OpenMPToLLVMIRTranslation.cpp.
convertOmpAtomicCapture()
static LogicalResult convertOmpAtomicCapture (omp::AtomicCaptureOp atomicCaptureOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 1362 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Block::begin(), convertAtomicOrdering(), convertBinOpToAtomic(), mlir::LLVM::ModuleTranslation::convertBlock(), mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::Block::getTerminator(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapBlock(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
convertOmpAtomicRead()
static LogicalResult convertOmpAtomicRead (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Convert omp.atomic.read operation to LLVM IR.
Definition at line 1235 of file OpenMPToLLVMIRTranslation.cpp.
References convertAtomicOrdering(), mlir::LLVM::ModuleTranslation::convertType(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
convertOmpAtomicUpdate()
static LogicalResult convertOmpAtomicUpdate (omp::AtomicUpdateOp & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP atomic update operation using OpenMPIRBuilder.
Definition at line 1292 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Block::begin(), convertAtomicOrdering(), convertBinOpToAtomic(), mlir::LLVM::ModuleTranslation::convertBlock(), mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::Block::getTerminator(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapBlock(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
convertOmpAtomicWrite()
static LogicalResult convertOmpAtomicWrite (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an omp.atomic.write operation to LLVM IR.
Definition at line 1258 of file OpenMPToLLVMIRTranslation.cpp.
References convertAtomicOrdering(), mlir::LLVM::ModuleTranslation::convertType(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
convertOmpCritical()
static LogicalResult convertOmpCritical (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'critical' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 291 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::get(), mlir::LLVM::ModuleTranslation::getLLVMContext(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpMaster()
static LogicalResult convertOmpMaster (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'master' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 264 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpOpRegions()
static llvm::BasicBlock* convertOmpOpRegions (Region & region, StringRef blockName, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, LogicalResult & bodyGenStatus, SmallVectorImpl< llvm::PHINode * > * continuationBlockPHIs = nullptr) static
Converts the given region that appears within an OpenMP dialect operation to LLVM IR, creating a branch from the sourceBlock to the entry block of the region, and a branch from any block with an successor-less OpenMP terminator to continuationBlock.
Populates continuationBlockPHIs with the PHI nodes of the continuation block if provided.
Definition at line 135 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::LLVM::detail::connectPHINodes(), mlir::LLVM::ModuleTranslation::convertBlock(), mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::forgetMapping(), mlir::Region::getBlocks(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::getTopologicallySortedBlocks(), mlir::LLVM::ModuleTranslation::lookupBlock(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::LLVM::ModuleTranslation::mapBlock().
Referenced by convertOmpCritical(), convertOmpMaster(), convertOmpOrderedRegion(), convertOmpParallel(), convertOmpSimdLoop(), convertOmpSingle(), convertOmpTarget(), convertOmpTaskgroupOp(), convertOmpTaskOp(), convertOmpWsLoop(), and inlineConvertOmpRegions().
convertOmpOrdered()
static LogicalResult convertOmpOrdered (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'ordered' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 517 of file OpenMPToLLVMIRTranslation.cpp.
References findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValues(), and mlir::success().
convertOmpOrderedRegion()
static LogicalResult convertOmpOrderedRegion (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'ordered_region' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 547 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::failure(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpParallel()
static LogicalResult convertOmpParallel (omp::ParallelOp opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts the OpenMP parallel operation to LLVM IR.
Definition at line 1005 of file OpenMPToLLVMIRTranslation.cpp.
References allocReductionVars(), collectReductionDecls(), collectReductionInfo(), convertOmpOpRegions(), mlir::failed(), mlir::failure(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), getProcBindKind(), inlineConvertOmpRegions(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
convertOmpReductionOp()
static LogicalResult convertOmpReductionOp (omp::ReductionOp reductionOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP reduction operation using OpenMPIRBuilder.
Expects the mapping between reduction variables and their private equivalents to have been stored on the ModuleTranslation stack. Currently only supports reduction within WsLoopOp and ParallelOp, but can be easily extended.
Definition at line 1459 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::WalkResult::advance(), mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), mlir::failure(), findReductionDecl(), mlir::Region::front(), mlir::Block::getArgument(), mlir::Operation::getParentOp(), inlineConvertOmpRegions(), mlir::WalkResult::interrupt(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapValue(), mlir::LLVM::ModuleTranslation::stackWalk(), and mlir::success().
convertOmpSections()
static LogicalResult convertOmpSections (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 580 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::emitError(), and mlir::success().
convertOmpSimdLoop()
static LogicalResult convertOmpSimdLoop (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP simd loop into LLVM IR using OpenMPIRBuilder.
Definition at line 1127 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
convertOmpSingle()
static LogicalResult convertOmpSingle (omp::SingleOp & singleOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP single construct into LLVM IR using OpenMPIRBuilder.
Definition at line 648 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpTarget()
static LogicalResult convertOmpTarget (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 2309 of file OpenMPToLLVMIRTranslation.cpp.
References collectMapDataFromMapOperands(), convertOmpOpRegions(), createAlteredByCaptureMap(), createDeviceArgumentAccessor(), mlir::failure(), findAllocaInsertPoint(), genMapInfos(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::Operation::getParentOfType(), getTargetEntryUniqueInfo(), handleDeclareTargetMapVar(), MapInfoData::IsDeclareTarget, mlir::LLVM::ModuleTranslation::lookupValue(), MapInfoData::MapClause, mlir::LLVM::ModuleTranslation::mapValue(), MapInfoData::OriginalValue, mlir::success(), and targetOpSupported().
convertOmpTargetData()
static LogicalResult convertOmpTargetData (Operation * op, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 1856 of file OpenMPToLLVMIRTranslation.cpp.
convertOmpTaskgroupOp()
static LogicalResult convertOmpTaskgroupOp (omp::TaskGroupOp tgOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP taskgroup construct into LLVM IR using OpenMPIRBuilder.
Definition at line 761 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpTaskOp()
static LogicalResult convertOmpTaskOp (omp::TaskOp taskOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP task construct into LLVM IR using OpenMPIRBuilder.
Definition at line 705 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
convertOmpTeams()
static LogicalResult convertOmpTeams (omp::TeamsOp op, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 666 of file OpenMPToLLVMIRTranslation.cpp.
convertOmpThreadprivate()
static LogicalResult convertOmpThreadprivate (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP Threadprivate operation into LLVM IR using OpenMPIRBuilder.
Definition at line 1513 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Operation::emitError(), mlir::Value::getDefiningOp(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::Operation::getResult(), mlir::LLVM::ModuleTranslation::lookupGlobal(), mlir::LLVM::ModuleTranslation::mapValue(), mlir::success(), and mlir::LLVM::ModuleTranslation::symbolTable().
convertOmpWsLoop()
static LogicalResult convertOmpWsLoop (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP workshare loop into LLVM IR using OpenMPIRBuilder.
Definition at line 838 of file OpenMPToLLVMIRTranslation.cpp.
References allocReductionVars(), collectReductionDecls(), collectReductionInfo(), convertOmpOpRegions(), mlir::failed(), mlir::failure(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), inlineConvertOmpRegions(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
convertRequiresAttr()
static LogicalResult convertRequiresAttr (Operation & op, omp::ClauseRequiresAttr requiresAttr, LLVM::ModuleTranslation & moduleTranslation) static
Converts the module-level set of OpenMP requires clauses into LLVM IR using OpenMPIRBuilder.
Definition at line 2522 of file OpenMPToLLVMIRTranslation.cpp.
convertToCaptureClauseKind()
static llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryKind convertToCaptureClauseKind (mlir::omp::DeclareTargetCaptureClause captureClasue) static
Definition at line 1558 of file OpenMPToLLVMIRTranslation.cpp.
convertToDeviceClauseKind()
static llvm::OffloadEntriesInfoManager::OMPTargetDeviceClauseKind convertToDeviceClauseKind (mlir::omp::DeclareTargetDeviceType deviceClause) static
Definition at line 1542 of file OpenMPToLLVMIRTranslation.cpp.
createAlteredByCaptureMap()
static void createAlteredByCaptureMap (MapInfoData & mapData, LLVM::ModuleTranslation & moduleTranslation, llvm::IRBuilderBase & builder) static
Definition at line 2233 of file OpenMPToLLVMIRTranslation.cpp.
References MapInfoData::BaseType, findAllocaInsertPoint(), MapInfoData::IsDeclareTarget, mlir::LLVM::ModuleTranslation::lookupValue(), and MapInfoData::MapClause.
Referenced by convertOmpTarget().
createDeviceArgumentAccessor()
static llvm::IRBuilderBase::InsertPoint createDeviceArgumentAccessor (MapInfoData & mapData, llvm::Argument & arg, llvm::Value * input, llvm::Value *& retVal, llvm::IRBuilderBase & builder, llvm::OpenMPIRBuilder & ompBuilder, LLVM::ModuleTranslation & moduleTranslation, llvm::IRBuilderBase::InsertPoint allocaIP, llvm::IRBuilderBase::InsertPoint codeGenIP) static
Definition at line 2169 of file OpenMPToLLVMIRTranslation.cpp.
References MapInfoData::MapClause, and MapInfoData::OriginalValue.
Referenced by convertOmpTarget().
findAllocaInsertPoint()
static llvm::OpenMPIRBuilder::InsertPointTy findAllocaInsertPoint (llvm::IRBuilderBase & builder, const LLVM::ModuleTranslation & moduleTranslation) static
Find the insertion point for allocas given the current insertion point for normal operations in the builder.
Definition at line 92 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::WalkResult::interrupt(), mlir::LLVM::ModuleTranslation::stackWalk(), and mlir::WalkResult::wasInterrupted().
Referenced by convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpOrdered(), convertOmpParallel(), convertOmpTarget(), convertOmpTaskgroupOp(), convertOmpTaskOp(), convertOmpWsLoop(), and createAlteredByCaptureMap().
findReductionDecl()
static omp::ReductionDeclareOp findReductionDecl (Operation & containerOp, omp::ReductionOp reduction) static
Searches for a reduction in a provided region and the regions it is nested in.
Definition at line 355 of file OpenMPToLLVMIRTranslation.cpp.
References findReductionDeclInContainer(), and mlir::Operation::getParentOp().
Referenced by convertOmpReductionOp().
findReductionDeclInContainer()
template<typename T > static std::optional<omp::ReductionDeclareOp> findReductionDeclInContainer (T container, omp::ReductionOp reduction) static
Returns a reduction declaration that corresponds to the given reduction operation in the given container.
Currently only supports reductions inside WsLoopOp and ParallelOp but can be easily extended as long as the given construct implements getNumReductionVars.
Definition at line 338 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by findReductionDecl().
genMapInfos()
static void genMapInfos (llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, DataLayout & dl, llvm::OpenMPIRBuilder::MapInfosTy & combinedInfo, MapInfoData & mapData, const SmallVector< Value > & devPtrOperands = {}, const SmallVector< Value > & devAddrOperands = {}, bool isTargetParams = false) static
Definition at line 1766 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpTarget().
getArrayElementSizeInBits()
uint64_t getArrayElementSizeInBits (LLVM::LLVMArrayType arrTy, DataLayout & dl)
Definition at line 1661 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::DataLayout::getTypeSizeInBits().
Referenced by getSizeInBytes().
getDeclareTargetRefPtrSuffix()
static llvm::SmallString<64> getDeclareTargetRefPtrSuffix (LLVM::GlobalOp globalOp, llvm::OpenMPIRBuilder & ompBuilder) static
Definition at line 1572 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::SymbolTable::Private.
Referenced by getRefPtrIfDeclareTarget().
getProcBindKind()
static llvm::omp::ProcBindKind getProcBindKind (omp::ClauseProcBindKind kind) static
Convert ProcBindKind from MLIR-generated enum to LLVM enum.
Definition at line 248 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpParallel().
getRefPtrIfDeclareTarget()
static llvm::Value* getRefPtrIfDeclareTarget (mlir::Value value, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 1595 of file OpenMPToLLVMIRTranslation.cpp.
References getDeclareTargetRefPtrSuffix(), mlir::Value::getDefiningOp(), mlir::LLVM::ModuleTranslation::getLLVMModule(), and mlir::LLVM::ModuleTranslation::getOpenMPBuilder().
Referenced by collectMapDataFromMapOperands().
getSizeInBytes()
llvm::Value* getSizeInBytes (DataLayout & dl, const mlir::Type & type, Operation * clauseOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation)
Definition at line 1678 of file OpenMPToLLVMIRTranslation.cpp.
References getArrayElementSizeInBits(), mlir::DataLayout::getTypeSizeInBits(), and mlir::LLVM::ModuleTranslation::lookupValue().
Referenced by collectMapDataFromMapOperands().
getTargetEntryUniqueInfo()
static bool getTargetEntryUniqueInfo (llvm::TargetRegionEntryInfo & targetInfo, omp::TargetOp targetOp, llvm::StringRef parentName = "") static
Definition at line 2047 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpTarget().
handleDeclareTargetMapVar()
static void handleDeclareTargetMapVar (MapInfoData & mapData, LLVM::ModuleTranslation & moduleTranslation, llvm::IRBuilderBase & builder) static
Definition at line 2093 of file OpenMPToLLVMIRTranslation.cpp.
References MapInfoData::IsDeclareTarget, MapInfoData::MapClause, and MapInfoData::OriginalValue.
Referenced by convertOmpTarget().
inlineConvertOmpRegions()
static LogicalResult inlineConvertOmpRegions (Region & region, StringRef blockName, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, SmallVectorImpl< llvm::Value * > * continuationBlockArgs = nullptr) static
Translates the blocks contained in the given region and appends them to at the current insertion point of builder.
The operations of the entry block are appended to the current insertion block, which is not expected to have a terminator. If set, continuationBlockArgs is populated with translated values that correspond to the values omp.yield'ed from the region.
Definition at line 402 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Block::back(), mlir::LLVM::ModuleTranslation::convertBlock(), convertOmpOpRegions(), mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::forgetMapping(), mlir::Region::front(), mlir::Operation::getOperands(), mlir::LLVM::ModuleTranslation::lookupValues(), mlir::LLVM::ModuleTranslation::mapBlock(), and mlir::success().
Referenced by convertOmpParallel(), convertOmpReductionOp(), convertOmpWsLoop(), makeAtomicReductionGen(), and makeReductionGen().
makeAtomicReductionGen()
static OwningAtomicReductionGen makeAtomicReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Create an OpenMPIRBuilder-compatible atomic reduction generator for the given reduction declaration.
The generator uses builder but ignores its insertion point. Returns null if there is no atomic region available in the reduction declaration.
Definition at line 488 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::failed(), mlir::Region::front(), mlir::Block::getArgument(), inlineConvertOmpRegions(), and mlir::LLVM::ModuleTranslation::mapValue().
Referenced by collectReductionInfo().
makeReductionGen()
static OwningReductionGen makeReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Create an OpenMPIRBuilder-compatible reduction generator for the given reduction declaration.
The generator uses builder but ignores its insertion point.
Definition at line 458 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::failed(), mlir::Region::front(), mlir::Block::getArgument(), inlineConvertOmpRegions(), and mlir::LLVM::ModuleTranslation::mapValue().
Referenced by collectReductionInfo().
targetOpSupported()
static bool targetOpSupported (Operation & opInst) static
Definition at line 2067 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Operation::emitError().
Referenced by convertOmpTarget().