MLIR: lib/Dialect/Bufferization/Transforms/OwnershipBasedBufferDeallocation.cpp File Reference
OwnershipBasedBufferDeallocation.cpp File Reference
#include "mlir/Dialect/Bufferization/IR/BufferDeallocationOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/Iterators.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::bufferization
Macros
#define GEN_PASS_DEF_OWNERSHIPBASEDBUFFERDEALLOCATION
Functions
static Value buildBoolValue (OpBuilder &builder, Location loc, bool value)
static bool isMemref (Value v)
static bool regionOperatesOnMemrefValues (Region &region)
Macro Definition Documentation
GEN_PASS_DEF_OWNERSHIPBASEDBUFFERDEALLOCATION
#define GEN_PASS_DEF_OWNERSHIPBASEDBUFFERDEALLOCATION
Definition at line 33 of file OwnershipBasedBufferDeallocation.cpp.
Function Documentation
buildBoolValue()
static Value buildBoolValue (OpBuilder & builder, Location loc, bool value) static
Definition at line 45 of file OwnershipBasedBufferDeallocation.cpp.
References mlir::OpBuilder::create(), and mlir::Builder::getBoolAttr().
isMemref()
static bool isMemref (Value v) static
Definition at line 49 of file OwnershipBasedBufferDeallocation.cpp.
References mlir::Value::getType(), and mlir::Type::isa().
Referenced by regionOperatesOnMemrefValues().
regionOperatesOnMemrefValues()
static bool regionOperatesOnMemrefValues (Region & region) static
Definition at line 465 of file OwnershipBasedBufferDeallocation.cpp.
References mlir::Block::getArguments(), mlir::WalkResult::interrupt(), isMemref(), and mlir::Region::walk().