MLIR: lib/Dialect/Mesh/Interfaces/ShardingInterface.cpp File Reference
ShardingInterface.cpp File Reference
#include "mlir/Dialect/Mesh/Interfaces/ShardingInterface.h"
#include "mlir/Dialect/Mesh/IR/MeshOps.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Support/Debug.h"
#include <algorithm>
#include <utility>
#include "mlir/Dialect/Mesh/Interfaces/ShardingInterface.cpp.inc"
Macros
#define DEBUG_TYPE "sharding-interface"
#define DBGS() (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Functions
static LogicalResult checkOperandAffineExprRecursively (AffineExpr expr, SmallVectorImpl< bool > &seenIds)
static FailureOr< llvm::SmallSet< unsigned, 2 > > checkOperandAffineExpr (AffineExpr expr, unsigned numDims)
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Definition at line 21 of file ShardingInterface.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "sharding-interface"
Definition at line 20 of file ShardingInterface.cpp.
Function Documentation
checkOperandAffineExpr()
static FailureOr<llvm::SmallSet<unsigned, 2> > checkOperandAffineExpr (AffineExpr expr, unsigned numDims) static
Definition at line 78 of file ShardingInterface.cpp.
References checkOperandAffineExprRecursively(), mlir::detail::enumerate(), mlir::failed(), and mlir::failure().
checkOperandAffineExprRecursively()
static LogicalResult checkOperandAffineExprRecursively (AffineExpr expr, SmallVectorImpl< bool > & seenIds) static
Definition at line 33 of file ShardingInterface.cpp.
References mlir::Add, mlir::Constant, mlir::DimId, mlir::failed(), mlir::failure(), mlir::AffineExpr::getKind(), mlir::Mul, and mlir::success().
Referenced by checkOperandAffineExpr().