MLIR: lib/Target/Cpp/TranslateToCpp.cpp File Reference
TranslateToCpp.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/EmitC/IR/EmitC.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/IndentedOstream.h"
#include "mlir/Target/Cpp/CppEmitter.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include <utility>
Macros
#define DEBUG_TYPE "translate-to-cpp"
Functions
template<typename ForwardIterator , typename UnaryFunctor , typename NullaryFunctor >
LogicalResult interleaveWithError (ForwardIterator begin, ForwardIterator end, UnaryFunctor eachFn, NullaryFunctor betweenFn)
Convenience functions to produce interleaved output with functions returning a LogicalResult.
template<typename Container , typename UnaryFunctor , typename NullaryFunctor >
LogicalResult interleaveWithError (const Container &c, UnaryFunctor eachFn, NullaryFunctor betweenFn)
template<typename Container , typename UnaryFunctor >
LogicalResult interleaveCommaWithError (const Container &c, raw_ostream &os, UnaryFunctor eachFn)
static LogicalResult printConstantOp (CppEmitter &emitter, Operation *operation, Attribute value)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ConstantOp constantOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::VariableOp variableOp)
static LogicalResult printOperation (CppEmitter &emitter, arith::ConstantOp constantOp)
static LogicalResult printOperation (CppEmitter &emitter, func::ConstantOp constantOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::AssignOp assignOp)
static LogicalResult printBinaryOperation (CppEmitter &emitter, Operation *operation, StringRef binaryOperator)
static LogicalResult printOperation (CppEmitter &emitter, emitc::AddOp addOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::DivOp divOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::MulOp mulOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::RemOp remOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::SubOp subOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CmpOp cmpOp)
static LogicalResult printOperation (CppEmitter &emitter, cf::BranchOp branchOp)
static LogicalResult printOperation (CppEmitter &emitter, cf::CondBranchOp condBranchOp)
static LogicalResult printOperation (CppEmitter &emitter, func::CallOp callOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CallOpaqueOp callOpaqueOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ApplyOp applyOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::CastOp castOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::IncludeOp includeOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::ForOp forOp)
static LogicalResult printOperation (CppEmitter &emitter, emitc::IfOp ifOp)
static LogicalResult printOperation (CppEmitter &emitter, func::ReturnOp returnOp)
static LogicalResult printOperation (CppEmitter &emitter, ModuleOp moduleOp)
static LogicalResult printOperation (CppEmitter &emitter, func::FuncOp functionOp)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "translate-to-cpp"
Definition at line 27 of file TranslateToCpp.cpp.
Function Documentation
interleaveCommaWithError()
template<typename Container , typename UnaryFunctor > LogicalResult interleaveCommaWithError (const Container & c, raw_ostream & os, UnaryFunctor eachFn) inline
Definition at line 62 of file TranslateToCpp.cpp.
References interleaveWithError().
Referenced by printOperation().
interleaveWithError() [1/2]
template<typename Container , typename UnaryFunctor , typename NullaryFunctor > LogicalResult interleaveWithError (const Container & c, UnaryFunctor eachFn, NullaryFunctor betweenFn) inline
Definition at line 55 of file TranslateToCpp.cpp.
References interleaveWithError().
interleaveWithError() [2/2]
template<typename ForwardIterator , typename UnaryFunctor , typename NullaryFunctor > LogicalResult interleaveWithError (ForwardIterator begin, ForwardIterator end, UnaryFunctor eachFn, NullaryFunctor betweenFn) inline
Convenience functions to produce interleaved output with functions returning a LogicalResult.
This is different than those in STLExtras as functions used on each element doesn't return a string.
Definition at line 39 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
Referenced by interleaveCommaWithError(), and interleaveWithError().
printBinaryOperation()
static LogicalResult printBinaryOperation (CppEmitter & emitter, Operation * operation, StringRef binaryOperator) static
Definition at line 261 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), mlir::Operation::getOperand(), and mlir::success().
Referenced by printOperation().
printConstantOp()
static LogicalResult printConstantOp (CppEmitter & emitter, Operation * operation, Attribute value) static
Definition at line 184 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getResult(), and mlir::success().
Referenced by printOperation().
printOperation() [1/23]
static LogicalResult printOperation (CppEmitter & emitter, arith::ConstantOp constantOp) static
Definition at line 232 of file TranslateToCpp.cpp.
References printConstantOp().
printOperation() [2/23]
static LogicalResult printOperation (CppEmitter & emitter, cf::BranchOp branchOp) static
Definition at line 337 of file TranslateToCpp.cpp.
References mlir::Block::getArguments(), mlir::Block::getSuccessor(), and mlir::success().
printOperation() [3/23]
static LogicalResult printOperation (CppEmitter & emitter, cf::CondBranchOp condBranchOp) static
Definition at line 357 of file TranslateToCpp.cpp.
References mlir::Block::getArguments(), mlir::raw_indented_ostream::indent(), mlir::success(), and mlir::raw_indented_ostream::unindent().
printOperation() [4/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::AddOp addOp) static
Definition at line 275 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [5/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::ApplyOp applyOp) static
Definition at line 465 of file TranslateToCpp.cpp.
printOperation() [6/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::AssignOp assignOp) static
Definition at line 248 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
printOperation() [7/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::CallOpaqueOp callOpaqueOp) static
Definition at line 415 of file TranslateToCpp.cpp.
printOperation() [8/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::CastOp castOp) static
Definition at line 478 of file TranslateToCpp.cpp.
printOperation() [9/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::CmpOp cmpOp) static
Definition at line 305 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [10/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::ConstantOp constantOp) static
Definition at line 216 of file TranslateToCpp.cpp.
References printConstantOp().
printOperation() [11/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::DivOp divOp) static
Definition at line 281 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [12/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::ForOp forOp) static
Definition at line 506 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), mlir::Region::getOps(), mlir::raw_indented_ostream::indent(), mlir::success(), and mlir::raw_indented_ostream::unindent().
printOperation() [13/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::IfOp ifOp) static
Definition at line 543 of file TranslateToCpp.cpp.
References mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::raw_indented_ostream::indent(), mlir::success(), and mlir::raw_indented_ostream::unindent().
printOperation() [14/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::IncludeOp includeOp) static
Definition at line 493 of file TranslateToCpp.cpp.
References mlir::success().
printOperation() [15/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::MulOp mulOp) static
Definition at line 287 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [16/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::RemOp remOp) static
Definition at line 293 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [17/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::SubOp subOp) static
Definition at line 299 of file TranslateToCpp.cpp.
References printBinaryOperation().
printOperation() [18/23]
static LogicalResult printOperation (CppEmitter & emitter, emitc::VariableOp variableOp) static
Definition at line 224 of file TranslateToCpp.cpp.
References printConstantOp().
printOperation() [19/23]
static LogicalResult printOperation (CppEmitter & emitter, func::CallOp callOp) static
Definition at line 403 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
printOperation() [20/23]
static LogicalResult printOperation (CppEmitter & emitter, func::ConstantOp constantOp) static
Definition at line 240 of file TranslateToCpp.cpp.
References printConstantOp().
printOperation() [21/23]
static LogicalResult printOperation (CppEmitter & emitter, func::FuncOp functionOp) static
Definition at line 609 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), mlir::raw_indented_ostream::indent(), interleaveCommaWithError(), and mlir::PreOrder.
printOperation() [22/23]
static LogicalResult printOperation (CppEmitter & emitter, func::ReturnOp returnOp) static
Definition at line 580 of file TranslateToCpp.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
printOperation() [23/23]
static LogicalResult printOperation (CppEmitter & emitter, ModuleOp moduleOp) static
Definition at line 599 of file TranslateToCpp.cpp.