MLIR: lib/Conversion/VectorToArmSME/VectorToArmSME.cpp File Reference
VectorToArmSME.cpp File Reference
#include "mlir/Conversion/VectorToArmSME/VectorToArmSME.h"
#include "mlir/Dialect/ArmSME/IR/ArmSME.h"
#include "mlir/Dialect/ArmSME/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/Support/Casting.h"
Functions
static bool isSplatZero (Type elemType, DenseElementsAttr val)
Returns true if 'val' is a splat of zero, false otherwise.
template<typename LoopBodyCallback >
static scf::ForOp createLoopOverTileSlices (PatternRewriter &rewriter, Location loc, Value initTile, LoopBodyCallback callback)
Generates a for loop over ZA tile slices where the induction variable is the tile slice index and each iteration yields a new tile.
Function Documentation
createLoopOverTileSlices()
template<typename LoopBodyCallback > static scf::ForOp createLoopOverTileSlices (PatternRewriter & rewriter, Location loc, Value initTile, LoopBodyCallback callback) static
Generates a for loop over ZA tile slices where the induction variable is the tile slice index and each iteration yields a new tile.
Loop body is built via the callback, which returns the next tile value.
Definition at line 32 of file VectorToArmSME.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIndexType(), mlir::Value::getType(), and mlir::OpBuilder::setInsertionPointToStart().
isSplatZero()
static bool isSplatZero (Type elemType, DenseElementsAttr val) static
Returns true if 'val' is a splat of zero, false otherwise.
Definition at line 20 of file VectorToArmSME.cpp.
References mlir::DenseElementsAttr::getSplatValue(), and mlir::DenseElementsAttr::isSplat().